name: Python Package using Conda

on: pull_request

permissions:
  checks: write
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.13.5
      uses: actions/setup-python@main
      with:
        python-version: '3.13.5'
    - name: Create the venv
      run: |
        python3 -m venv $GITHUB_WORKSPACE/.venv
        source $GITHUB_WORKSPACE/.venv/bin/activate
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Install Linters
      run: |
        pip install flake8 black
        # # stop the build if there are Python syntax errors or undefined names
        # flake8 ./hexgen --count --select=E9,F63,F7,F82 --show-source --statistics
        # # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 ./hexgen --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Linters flake8 and black
      uses: wearerequired/lint-action@v2.3.0
      with:
        auto_fix: true
        black: true
        black_dir: ./hexgen
        black_auto_fix: true
        flake8: true
        flake8_dir: ./hexgen
        flake8_auto_fix: true
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --junit-xml=test-report.xml
    - name: Test Report
      uses: dorny/test-reporter@v3.0.0
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: Hexgen Tests            # Name of the check run which will be created
        path: test-report.xml         # Path to test results
        reporter: python-xunit        # Format of test results
